[Тестовое задание] Убрать лишние преобразования типов данных в выводе декомпилятора
sudo-team-company/OpenCLDecompiler pull request #24
Opened 2024-10-08 20:23 UTC by FollowJust

### Выполнил Гладких Андрей, студент 2-го курса магистратуры ИТМО, группа M4238

<details><summary>Условия тестового задания</summary><p>

Необходимо убрать лишние преобразования типов данных в выводе декомпилятора.

Пример: на изображении декомпилятор переменные типа int при сравнении приводит к тому же типу int.
(https://github.com/sudo-team-company/OpenCLDecompiler/blob/develop/tests/branching_kernels/if_else_in_if/if_else_in_if_dcmpl.cl)

Требования к коду решения:
- все тесты завершаются успешно, при этом разрешается их менять в соответствии с целью задания (настроено в Github Actions)
- линтер не выдает предупреждений (тоже настроено в Github Actions)
- pre-commit run --all-files успешно выполняется (https://pre-commit.com)

Для успешного выполнения тестового задания допустимо убрать не все лишние преобразования типов, но для общего случая задача должна быть решена.

Актуальный код находится в ветке develop. Для сдачи задания нужно будет создать PR в неё.

</p></details>

Для решения общего случая добавил в check_reg_for_val проверку необходимости приведения типа на основе сравнения суффикса инструкции с:
- значением типа, который хранится в регистре
- типом числа. Отдельно рассмотрены случаи приведения отрицательных значений к беззнаковым типам

Также заметил в тестах, что лишнее приведение есть у инструкций чтения (`flat_load`) и записи (`flat_store`) при работе с глобальной памятью и у инструкции нахождения минимума `s_min`. Исправил для каждого случая проблему отдельно.

Исправления в тестах связаны с изменениями в `_hands.cl` файлах в связи с удалением лишних приведений типов.

2024-10-18 12:51 UTC, RubyUmbra requested changes
В общем, было сделано то что ожидалось. Есть два критических бага. Остальные проблемы, скорее всего, не связаны с текущей задачей.

Пояснения к обозначениям:
- `[1.*]` -- Критические баги, обязательные к исправлению.
- `[2.*]` -- Неочевидное поведение: различие вывода для похожих случаев. Необходимо пояснить причину различий, желательно исправить.
- `[3.*]` -- Ошибки, унаследованные от старых багов. Пояснения причин приветствуются.

Ошибки `[1.*]` отмечены все, для остальных отмечены несколько нахождений.

2024-10-18 12:51 UTC, RubyUmbra commented on tests/branching_kernels/if_else_1_label/if_else_1_label_hands.cl
> +    var0 = var2;
[1.1]
Изменилась семантика кода -- была запись в память, стало присвоение адреса.

2024-10-18 12:51 UTC, RubyUmbra commented on tests/branching_kernels/if_else_2_labels/if_else_2_labels_hands.cl
> +    var1 = var4;
[1.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/branching_kernels/if_else_and_if_else/if_else_and_if_else_hands.cl
> +    data[get_global_id(2)] = min(x, y);
[1.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/loop_block/loop_block_hands.cl
> +            var5 = var3;
[1.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/loop_general/loop_general_hands.cl
> +            var4 = (ulong)var5 + (var3);
[3.1]
Тут нужно пояснить почему так получилось. `var3` и `var5` типа `int`, а `var4` типа `uint`. Почему приведение типа убралось только у `var3`?

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/loop_general_dec/loop_general_dec_hands.cl
> +            var4 = (ulong)var5 + (var3);
[3.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/loop_general_dec/loop_general_dec_hands.cl
> +        var2 = (var3) + (ulong)(var5 + (-1)) + 1;
[3.2]
`var2` -- `int`
`var3` -- `int`
`var5` -- `int` => `var5 + (-1)` -- `int`
Надо разобраться почему остался каст для `var5 + (-1)`.

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/loop_with_break_kernels/loop_with_break_kernels_hands.cl
> +            var7 = var6;
[1.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/simple_loop_kernels/simple_loop_kernels_hands-gfx.cl
> +            var14 = var13;
[1.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/simple_loop_kernels/simple_loop_kernels_hands-gfx.cl
> +            var10 = var9;
[1.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/simple_loop_kernels/simple_loop_kernels_hands-gfx.cl
> +            var12 = var11;
[1.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/simple_loop_kernels/simple_loop_kernels_hands.cl
> +            var12 = var11;
[1.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/simple_loop_kernels/simple_loop_kernels_hands.cl
> +            var12 = var11;
[1.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/loops_kernels/simple_loop_kernels/simple_loop_kernels_hands.cl
> +            var12 = var11;
[1.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/real_kernels/bellmanFordInit_ver1/bellmanFordInit_ver1_hands.cl
> +        if (var1 < (double)1e12) {
[1.2]
Константы вида `1e12` не требуют приведения к типу `double`.

2024-10-18 12:51 UTC, RubyUmbra commented on tests/linear_kernels/addition/addition_hands-gfx.cl
> +    data[get_global_id(2)] = (ulong)x + get_global_id(2);
[2.1]
В чём разница между 42 и 43 строками? Почему в 42 приведение типа осталось?

2024-10-18 12:51 UTC, RubyUmbra commented on tests/linear_kernels/addition/addition_hands-gfx.cl
> +    data[get_global_id(2)] = (ulong)get_local_id(2) + get_global_id(2);
[2.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/linear_kernels/addition/addition_hands-gfx.cl
> +    data[get_global_id(2)] = (ulong)get_global_size(2) + get_global_id(2);
[2.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/linear_kernels/addition/addition_hands-gfx.cl
> +    data[get_global_id(2)] = x + 4;
[2.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/linear_kernels/addition/addition_hands-gfx.cl
> +    data[get_global_id(2)] = (ulong)get_global_size(2) + x;
[3.3]
Скорее всего тут какой-то баг, не относящийся к заданию, но результат выглядит очень странно.

| value | type|
|---------|-------|
| `get_global_size(0)` | `size_t` aka `ulong` |
| `x` | `int` |
| `data[...]` | `int` |

То есть с точки зрения типов получается что-то такое:
```
<int> <- (ulong)<ulong> + <int>
```

2024-10-18 12:51 UTC, RubyUmbra commented on tests/linear_kernels/subtraction/subtraction_hands-gfx.cl
>      data[get_global_id(2)] = (ulong)x + (ulong)(-2);
[2.1]

2024-10-18 12:51 UTC, RubyUmbra commented on tests/linear_kernels/subtraction/subtraction_hands-gfx.cl
> +    data[get_global_id(2)] = (ulong)get_global_size(2) + 0xfe;
[2.1]

2024-10-18 12:51 UTC, RubyUmbra commented on src/instructions/flat/flat_store.py
> +                        var = "*(" + make_opencl_type(self.decompiler_data.names_of_vars[var]) + "*)(" + var + ")"
Скорее всего тут потерян `else` как в [src/instructions/flat/flat_load.py#R110-R111](https://github.com/sudo-team-company/OpenCLDecompiler/pull/24/files#diff-8930b1fe2b71fcc95e266d11f9295011978c807fba2e71413aef3b6abdd9d4eaR110-R111).

Думаю его добавление пофиксит [1.1].

2024-10-27 20:37 UTC, FollowJust commented
1. Исправил проблему [1.1]
2. Cделал так, чтобы приведения не делались, если:
- типы имеют одинаковый знак, при этом исходный тип "влезает" в новый (e.g. `u16 -> u32`,  `f32->f64`)
- приводится float с дробной частью равной нулю в знаковый тип (e.g. `12.0`, `-123.0`) или в беззнаковый тип (e.g. `12.0`)
3. Б*о*льшая часть ошибок [2.x] была исправлена с этими изменениями

2024-10-27 20:44 UTC, FollowJust commented on tests/loops_kernels/loop_general/loop_general_hands.cl
> +            var4 = (ulong)var5 + (var3);
Дело в том, что в функцию приходит выражение `x * var4`, которое имеет `data_type = u32`. Поэтому оно не приводится.

2024-10-27 20:51 UTC, FollowJust commented on tests/linear_kernels/addition/addition_hands-gfx.cl
> +    data[get_global_id(2)] = (ulong)get_global_size(2) + x;
Тут логика такая - функция `make_op` в данном случае вызывается с `suffix = i32`, `type0 = ulong`, `type1 = ulong`. Для регистра, в котором хранится `x`, известен тип - `i32`, поэтому он не приводится. А для регистра, в котором хранится выражение `get_global_size(0)`, `data_type` не выставлен. Так как это не число, то для перестраховки оно приводится.

2024-10-27 21:00 UTC, FollowJust commented on tests/linear_kernels/addition/addition_hands-gfx.cl
> +    data[get_global_id(2)] = x + 4;
Я бы сказал, что это ошибка [3.x], потому что причиной тому служит то, что для `x + 4` `makeop` вызывается с `suffix = i32`, а для `x + 2` с `suffix = u16`. При этом `x` имеет `data_type = i32`, поэтому во втором случае он приводится. Тип `(ulong)`  берется также из аргументов функции `make_op`

2024-11-08 10:11 UTC, RubyUmbra requested changes
Приведение констант в экспоненциальной записи [1.2] не исправлено. В новой функции опечатка в имени. Это надо поправить.
В остальном всё отлично.

2024-11-08 10:11 UTC, RubyUmbra commented on src/decompiler_data.py
> +def chech_value_needs_cast(value, from_type, to_type) -> bool:
Опечатка в имени функции.

2024-11-08 10:11 UTC, RubyUmbra commented on tests/real_kernels/bellmanFordInit_ver1/bellmanFordInit_ver1_hands.cl
> +        if (var1 < (double)1e12) {
Не исправлено.

2024-11-09 09:36 UTC, FollowJust commented
Добавил обработку чисел в экспоненциальной записи и поправил опечатку.

2024-11-09 11:30 UTC, RubyUmbra approved these changes
Всё отлично, задача выполнена.

2024-11-09 11:31 UTC, merged